ALTER TABLE inventory_items
ADD COLUMN IF NOT EXISTS variant TEXT,
ADD COLUMN IF NOT EXISTS purchase_price NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS market_value NUMERIC(12,2) NOT NULL DEFAULT 0;